### PR TITLE
added setup info for caddy v2 in docs

### PR DESCRIPTION
**Pull request by securisec**
## Description
The instructions in the docs are for v1, and does not apply to v2 as directives such as `transparent` and `websockets` so no longer exists. Instead headers are used to use these features. 

Also, `proxy` has been renamed to `reverse_proxy` in v2. 

This pull request simply updates the docs with the proper setup for Caddy v2.

## How Has This Been Tested?
This was tested in a Google cloud f1-micro with Caddy versions `2.2.0-rc3` and `2.1.0`. The only files modified during testing was the `Caddyfile` which included the as documented headers setup and ran with `caddy run`. Inlets was ran as already documented. 

Testing was also conducted against both an express server and python built in http server and success from both.  

## How are existing users impacted? What migration steps/scripts do we need?
0

## Checklist:

I have:

- [x] updated the documentation and/or roadmap (if required)
- [x] read the [CONTRIBUTION](https://github.com/inlets/inlets/blob/master/CONTRIBUTING.md) guide
- [x] signed-off my commits with `git commit -s`
- [ ] added unit tests

### CODE REVIEW

**Comment by alexellis** [comment]
Hi there, thank you for your interest.

> "No test required."

Tests are required, this is why we have a PR template that asks specifically for testing.

Alex

**Comment by joshrahman** [comment]
Thank you @alexellis. I wrote no tests required because there are no code changes only documentation changes. I am not sure what tests to include for documentation...

**Comment by alexellis** [comment]
Whilst you don't need to provide automated unit tests, you do need to say how the configuration was tested.

**Comment by securisec** [comment]
> Whilst you don't need to provide automated unit tests, you do need to say how the configuration was tested.

Understood. I updated the description for the pull request with the tests that were done to make sure everything works as expected.

**Comment by alexellis** [comment]
Thank you, that's exactly what was required 👍 

Do take a look at [inlets PRO too](https://inlets.dev) which enables you to run Caddy on your own host, and multiplex many different websites and protocols.

**Pull request merged**
