### PR TITLE
Add other port-forwarding tools.

### PR DESCRIPTION
**Pull request by wi1dcard**
## Description

Add a couple of port-forwarding tools in README.md.

## How Has This Been Tested?

None.

## How are existing users impacted? What migration steps/scripts do we need?

None.

## Checklist:

I have:

- [x] updated the documentation and/or roadmap (if required)
- [x] read the [CONTRIBUTION](https://github.com/inlets/inlets/blob/master/CONTRIBUTING.md) guide
- [x] signed-off my commits with `git commit -s`
- [ ] added unit tests

### CODE REVIEW

**Comment by alexellis** [comment]
Hi, I'm not looking to build a page like "awesome-port-forwarding-tools", this was just a small index of projects I know personally.

Thanks for the interest though.

You may want to submit these links to: https://github.com/ramitsurana/awesome-kubernetes

Alex

**Comment by wi1dcard** [comment]
Alright, I just thought that a list of alternatives would be great.

**Comment by alexellis** [comment]
No worries

**Pull request closed without merging**
