### PR TITLE
fix relative link in documentation

### PR DESCRIPTION
**Pull request by PhilETaylor**
Simply fixes the link to the correct documentation

### CODE REVIEW

**Comment by PhilETaylor** [comment]
well take it or leave it... its only a documentation link, and the commit is GPG signed and created on GitHub web interface which doesn't support the sign-off feature... it seams.

**Comment by alexellis** [comment]
Hi there, Derek gave you a one-liner to fix this, do you want to go ahead?

FYI for sign-off comments in the UI, simply add a line in your commit:

```
Signed-off-by: ....
```

**Comment by PhilETaylor** [comment]
You can't edit the commit comments once submitted - through the Github Interface

And before I could clone the repo to my local machine, and submit the change - you closed this... not a good first impression to contributors.

**Comment by alexellis** [comment]
Thank you for flagging up the broken link. Here's an example of one I did just now: https://github.com/inlets/inlets/commit/5822fe2fb3651b5b9279205f23e81ecfa134f39a

Derek's just doing his job, [the contributing guide does explain why signing off is required](https://github.com/inlets/inlets/blob/master/CONTRIBUTING.md), as does the PR template (which you deleted?)

**Comment by PhilETaylor** [comment]
Im sorry that you enforce this kind of thing just for updating documentation. Total overkill.

**Comment by PhilETaylor** [comment]
This project seems to overlook completely that a quick fix like this - made with the Github Web Interface on an iPhone while not at a desk - cannot be signed off in the manner the project demands === Thus less contributions.

**Comment by alexellis** [comment]
We have a contribution guide, which everyone needs to follow to keep things fair and balanced.

> well take it or leave it...

^ this kind of language implied that you were not willing to work with the process, so I've gone ahead and fixed the link.

Feel free to raise an issue, or to message us on Slack if you find any other typos or broken links.

**Pull request closed without merging**
