### PR TITLE
Bump remotedialer dependency

### PR DESCRIPTION
**Pull request by alexellis**
Signed-off-by: Alex Ellis (OpenFaaS Ltd) <alexellis2@gmail.com>

## Description

Bump remotedialer dependency

## How Has This Been Tested?

Tested with a local tunnel and a simple HTTP server

## How are existing users impacted? What migration steps/scripts do we need?

Further testing would be beneficial and a review from @ibuildthecloud before merging.

## Checklist:

I have:

- [x] updated the documentation and/or roadmap (if required)
- [x] read the [CONTRIBUTION](https://github.com/inlets/inlets/blob/master/CONTRIBUTING.md) guide
- [x] signed-off my commits with `git commit -s`
- [ ] added unit tests

### CODE REVIEW

**Comment by alexellis** [comment]
@ibuildthecloud said he wasn't sure the new context was introduced erroneously. Waiting for further feedback.

**Comment by ibuildthecloud** [comment]
LGTM

**Comment by amarruedo** [comment]
Hi there!

Since this is still pending to be mergerd... would it be possible to upgrade `remotedialer` to version `v0.2.4` or greater, so `inlets` client honors `http_proxy` environment variable, thus enabling tunnels on machines behind a corporate proxy?

Thanks for the great work!

**Comment by alexellis** [comment]
Hi both, it's possible that the proxy code suffered a regression when moving to remotedialer. I'm going to cut a release with the latest version available. Let me know what you find with your testing.

Alex

**Comment by alexellis** [comment]
@amarruedo feel free to submit your use-case at SALTO Systems to the ADOPTERS.md file #117 

Alex

**Comment by alexellis** [comment]
The patch was released for you @amarruedo, can you respond please ?

**Comment by amarruedo** [comment]
H!

I can confirm that it works.

Thanks for the release.

**Comment by alexellis** [comment]
You're welcome.

**Pull request merged**
