### PR TITLE
Running Exit Node on Google Compute Engine

### PR DESCRIPTION
**Pull request by DazWilkin**
Wrote a short tutorial to show how to run an Inlets Exit Node on Google Compute Engine:

https://pretired.dazwilkin.com/posts/200122/

## Checklist:

I have:

- [ ] updated the documentation and/or roadmap (if required)
- [ ] read the [CONTRIBUTION](https://github.com/inlets/inlets/blob/master/CONTRIBUTING.md) guide
- [ ] signed-off my commits with `git commit -s`
- [ ] added unit tests

### CODE REVIEW

**Comment by utsavanand2** [comment]
Hi @DazWilkin!
Thanks for the blog-post! It would be nice if you could sign-off your commit with a `git commit -s` as described in our [contribution](https://github.com/inlets/inlets/blob/master/CONTRIBUTING.md) guide

**Comment by utsavanand2** [comment]
You can also resolve the merge conflicts, by reseting you commit with a
`git reset HEAD~1` # Considering you have a single commit
then,
`git pull --rebase`
`git add .`
`git commit -s`

I guess these merge conflicts are due to the recent changes in the README file of the inlets repo

Thanks!

**Comment by DazWilkin** [comment]
Thanks @utsavanand2 

Hopefully this does the trick! I'd thought that I had signed it off, apologies.

**Comment by utsavanand2** [comment]
Thanks for the PR @DazWilkin no need for apology, I'm glad you took the time to try it out and write something about it!

**Comment by alexellis** [comment]
> This branch cannot be rebased due to conflicts

Looks like we need a rebase

**Comment by alexellis** [comment]
Something like this should do it:

```
git reset HEAD~2
git add .
git commit -s

git push origin --force
```

**Comment by alexellis** [comment]
Sorry for what may be a surprising contribution experience :)

Thank you for the blog post. If you'd like to join us on Slack, we'd love to hear more.

**Comment by alexellis** [comment]
@utsavanand2 would you mind taking this PR on and saving Daz from the headache? :-)

If you don’t get to it, I’ll do it.

Btw, I’ve tweeted the page out as @inletsdev, nice post.

We also have a tool called inletsctl which can automate the provisioning.. do check that out too inlets/inletsctl

**Comment by utsavanand2** [comment]
Sure!

**Comment by DazWilkin** [comment]
Sorry for the inconvenience guys! :-(

**Comment by utsavanand2** [comment]
@DazWilkin No issues at all. 😉

**Comment by utsavanand2** [comment]
Here it is @alexellis https://github.com/inlets/inlets/pull/159

**Pull request closed without merging**
